Agregado TUGpy, grupo de usuarios de TeX / LaTeX
tejuguasu/directorio pull request #12
Opened 2024-03-21 13:49 UTC by thegreyshadow

Se agrega el grupo TUG-py para usuarios de TeX y LaTeX y similiares.

2024-03-21 14:04 UTC, tejuguasu requested changes

2024-03-21 14:04 UTC, tejuguasu commented on README.md
> +| TUGpy            | [![][ico-telegram]](https://t.me/TUGpy) | Grupo de usuarios de TeX / LaTeX y similares de Paraguay |
TeX Users Group (TUG) no es algo que no iniciados enitendan.
Si te parece bien, listarlo como LaTeX / TeX, y agregar TUG en datos extra.

2024-03-21 14:49 UTC, thegreyshadow reviewed
Me parece bien pero no me deja aprobar el cambio propuesto (perdón no soy muy ducho en git/github)

2024-03-21 14:51 UTC, tejuguasu commented on README.md
> +| TUGpy            | [![][ico-telegram]](https://t.me/TUGpy) | Grupo de usuarios de TeX / LaTeX y similares de Paraguay |
Mandá nomás el nuevo commit con el cambio :)

2024-03-21 14:54 UTC, tejuguasu requested changes

2024-03-21 14:55 UTC, tejuguasu commented
> Me parece bien pero no me deja aprobar el cambio propuesto (perdón no soy muy ducho en git/github)

Ah, porque fue un comentario, no fue usando una sugerencia de cambio.

2024-03-21 14:55 UTC, thegreyshadow commented on README.md
> +| LaTeX / TeX       | [![][ico-telegram]](https://t.me/ti_py) | TUG (TeX / LaTeX Users Group) Paraguay |
Perdón, ahora corrijo

2024-03-21 17:35 UTC, tejuguasu commented
> Ahora sí, espero que los cambios sean los esperados.

Estaba bien en la sección "Lenguajes y entornos de programación" cuidando el orden alfabético. Último cambio :)

2024-03-25 13:40 UTC, thegreyshadow commented on README.md
> +| LaTeX / TeX       | [![][ico-telegram]](https://t.me/ti_py) | TUG (TeX / LaTeX Users Group) Paraguay |
Hecho el cambio, espero que esté bien ahora. Perdón por la tardanza. Life happened

2024-03-25 13:40 UTC, thegreyshadow commented
Agregado el cambio, espero que ahora esté bien

2024-03-25 14:00 UTC, tejuguasu requested changes
Actualizar link al grupo

2024-03-25 14:03 UTC, tejuguasu approved these changes

2024-03-25 14:04 UTC, merged