Agregando algunos grupos y canales
tejuguasu/directorio pull request #9
Opened 2022-09-19 20:36 UTC by tawhk

Vi que muchos compartían este repo en los Telegram así que decicí actualizar un poco con la lista que tenía a mano.

2022-09-19 20:55 UTC, tejuguasu requested changes
¡Muy valiosos aportes! Dejo algunas sugerencias y preguntas.

2022-09-19 20:55 UTC, tejuguasu commented on README.md
> +* TIPY Joda https://t.me/tipyjoda
TIPY Joda no tiene muchos integrantes, ¿aporta algo que no esté en los otros grupos?
Ídem respecto a FLISOL.

2022-09-19 20:55 UTC, tejuguasu commented on README.md
> +* Domotica https://t.me/DomoticaPy
Supongo que Domotica también debería ir dentro de Áreas

2022-09-19 20:55 UTC, tejuguasu commented on README.md
> +* PYOSCON https://t.me/pyoscon
PYOSCON tiene solo 6 suscriptores, ¿aporta algo distinto a los otros grupos de tecnología donde ya se habla de open source?

2022-09-19 21:18 UTC, tawhk commented on README.md
> +* Docker https://t.me/dockerparaguay
Tal vez podríamos incluir eso en el guidelines. No me fijé que se usaba orden alfabético. Voy a hacer las modificaciones.

2022-09-19 21:24 UTC, tawhk commented on README.md
> +* PowerBI & Analytics https://t.me/pbi_analytics_py
Concuerdo. Dudé mucho en dónde incluir, pero me dejé llevar por la definición estricta de lenguaje. Lenguaje y entornos de programación suena bien para mí.

2022-09-19 21:32 UTC, tawhk commented on README.md
> +* Proyectos Beta https://t.me/proyectosbeta
Es un grupo bastante activo moderado por el Ing. José González von Schmeling, miembro de OSM Paraguay y mantainer de la web proyectosbeta.net.

2022-09-19 21:35 UTC, tawhk commented on README.md
> +* TIPY Joda https://t.me/tipyjoda
Aunque no tenga muchos integrantes es bastante activo y me parece que su finalidad es evitar spam de memes en el grupo TIPY principal y cumple bastante bien ese objetivo. 
El grupo de FLISOL Paraguay es muy importante para la comunidad de Software Libre, aunque su actividad se limita mayormente a Abril y meses cercanos ya que en esa fecha se organiza la principal actividad de la comunidad.

2022-09-19 21:37 UTC, tawhk commented on README.md
> +* PYOSCON https://t.me/pyoscon
Es una comunidad en crecimiento, un proyecto que aún no despega bien. Podríamos obviar hasta que haga más ruido 😅

2022-09-19 21:57 UTC, tejuguasu commented on README.md
> +* Docker https://t.me/dockerparaguay
Tenés razón, actualicé `CONTRIBUTING.md`.

2022-09-19 21:58 UTC, tejuguasu commented on README.md
> +* Unix https://t.me/nixpy
Definitivamente justifica mantenerlos por separado si el contenido de las conversaciones es tan distinto como decís.

2022-09-19 21:59 UTC, tejuguasu commented on README.md
> +* PowerBI & Analytics https://t.me/pbi_analytics_py
Podés incluir entonces el renombrado a `Lenguajes y entornos de programación` en este PR, si estás de acuerdo.

2022-09-19 22:00 UTC, tejuguasu commented on README.md
> +* Proyectos Beta https://t.me/proyectosbeta
Me lo vendiste 😄

2022-09-19 22:01 UTC, tejuguasu commented on README.md
> +* TIPY Joda https://t.me/tipyjoda
Ok. Cuando tiene sentido creo que habría que agregar una pequeña descripción en la misma línea.
Llegué a considerar pasar a una estructura de tabla, pero postergué la decisión hasta realmente necesitarlo, tal vez llegó el momento.

2022-09-19 22:02 UTC, tejuguasu commented on README.md
> +* PYOSCON https://t.me/pyoscon
Supongo que tiene sentido incluirlo agregando la pequeña descripción

2022-09-19 22:19 UTC, tawhk commented on README.md
> +* TIPY Joda https://t.me/tipyjoda
Sí. Los grupos suelen tener descripción propia. Podríamos incluirlos. O alguna descripción alterna. 
Creo que quedaría bien:
* nombre descripción link

2022-09-20 00:05 UTC, tejuguasu commented on README.md
> +* TIPY Joda https://t.me/tipyjoda
Podemos mejorar los demás comentarios (orden alfabético y reubicación) y en un siguiente PR convertimos a nombre/desc/link, o tabla

2022-09-20 13:02 UTC, tejuguasu requested changes
Almost there

2022-09-20 13:02 UTC, tejuguasu commented on README.md
> +* Genexus https://t.me/genexuspy
Genexus → Golang → GraphQL

2022-09-20 13:02 UTC, tejuguasu commented on README.md
> +* Domotica https://t.me/DomoticaPy
Debajo de DevOps

2022-09-20 13:02 UTC, tejuguasu commented on README.md
> +* FLISOL Paraguay https://t.me/flisolpy
Abajo de Finanzas

2022-09-20 13:11 UTC, tawhk commented on README.md
> +* Domotica https://t.me/DomoticaPy
Me olvido de ordenar, sorry. Allá voy.

2022-09-20 13:26 UTC, tejuguasu approved these changes
¡Excelentes aportes!

2022-09-20 13:26 UTC, merged